[program:guest-manager-automated-system]
process_name=%(program_name)s_%(process_num)02d
command=php /Users/ahmed/Sites/guest-manager-laravel/artisan queue:work --sleep=3 --tries=3 --timeout=60 --memory=128
autostart=true
autorestart=true
user=ahmed
numprocs=1
redirect_stderr=true
stdout_logfile=/Users/ahmed/Sites/guest-manager-laravel/storage/logs/queue-worker.log
stopwaitsecs=3600

[program:guest-manager-scheduler]
process_name=%(program_name)s_%(process_num)02d
command=php /Users/ahmed/Sites/guest-manager-laravel/artisan schedule:work
autostart=true
autorestart=true
user=ahmed
numprocs=1
redirect_stderr=true
stdout_logfile=/Users/ahmed/Sites/guest-manager-laravel/storage/logs/scheduler.log
stopwaitsecs=3600




